# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/mojito-leicacamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/mojito-leicacamera

PRODUCT_COPY_FILES += \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/default-permissions/miuicamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/miuicamera-permissions.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.front.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/android.hardware.camera.full.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.full.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/android.hardware.camera.raw.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.hardware.camera.raw.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/privapp-permissions-mimoji.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-mimoji.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/privapp-permissions-miui.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miui.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/privapp-permissions-miuicamera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuicamera.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/privapp-permissions-miuiextraphoto.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuiextraphoto.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/privapp-permissions-miuigallery.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuigallery.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/permissions/privapp-permissions-miuiscanner.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuiscanner.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libAIPOSE.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libAIPOSE.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libCameraEffectJNI.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libDocumentProcess.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libDocumentProcess.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libMiVideoSDK.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libMiVideoSDK.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libSNPE.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libSNPE.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libYuvWatermark.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libYuvWatermark.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libarcsoft_single_chart_calibration.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libarcsoft_single_chart_calibration.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libc++.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libc++.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libc++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libc++_shared.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_algoup_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_algoup_jni.xiaomi.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_memory_util_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_memory_util_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_mi_handgesture.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_mi_handgesture.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_mianode_jni.xiaomi.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_mianode_jni.xiaomi.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_requestutil_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_requestutil_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_video_mein_algo_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_video_mein_algo_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcamera_yuv_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcamera_yuv_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libcameraservice.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libdmabufheap.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libdmabufheap.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libhidltransport.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libhidltransport.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libijkffmpeg.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libijkffmpeg.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libijkplayer.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libijkplayer.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libijksdl.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libijksdl.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libion.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libion.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libjpeg.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmialgo_saliency_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmiffmpeg.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmiffmpeg.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmiocr_wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmiocr_wrapper.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmiuiblursdk.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmiuiblursdk.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libmulti-wakeup-engine.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libmulti-wakeup-engine.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/librender_engine.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/librender_engine.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_domains_v2.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_domains_v2.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_skel.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_v65_domains_v2_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_v65_domains_v2_skel.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_v66_domains_v2_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libsnpe_dsp_v66_domains_v2_skel.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libsymphony-cpu.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libsymphony-cpu.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libtailor.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libtailor.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libturbojpeg.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libturbojpeg.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libvideo_extra_color_converter.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libvideo_extra_color_converter.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libvideo_extra_interpolator.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libvideo_extra_interpolator.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libxcrash.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libxcrash.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libxcrash_dumper.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libxcrash_dumper.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiCamera/lib/arm64/libyuv.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiCamera/lib/arm64/libyuv.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libMNN.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libMNN.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libauto_crop_c++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libauto_crop_c++_shared.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libautocrop.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libautocrop.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libc++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libc++_shared.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libcommon.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libcommon.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libdoc_photo.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libdoc_photo.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libdoc_photo_c++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libdoc_photo_c++_shared.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libdoc_photo_process.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libdoc_photo_process.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_arcsoft_dualcam_refocus.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_arcsoft_dualcam_refocus.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_arcsoft_portrait_lighting.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_arcsoft_portrait_lighting.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_arcsoft_portrait_lighting_c.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_arcsoft_portrait_lighting_c.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_mpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libgallery_mpbase.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmegvii_bokeh_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmegvii_bokeh_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_ai_vision.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_ai_vision.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_autocrop.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_autocrop.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_portrait.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_portrait.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_utils_extraphoto.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmialgo_utils_extraphoto.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmibokeh_gallery.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmibokeh_gallery.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmibrain_relighting_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmibrain_relighting_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmicamera_dual_bokeh_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmicamera_dual_bokeh_jni.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_dynSpot.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_dynSpot.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_effect.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_effect.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_gpf.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_gpf.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_proc.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_bokeh_proc.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_refocus_bokeh.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmiphone_refocus_bokeh.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmisr.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmisr.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmiuiblursdk.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmiuiblursdk.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmotion_photo.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmotion_photo.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmotion_photo_c++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmotion_photo_c++_shared.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libmotion_photo_mace.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libmotion_photo_mace.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/librefocus.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/librefocus.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/librefocus_meitu.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/librefocus_meitu.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/librefocus_mibokeh.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/librefocus_mibokeh.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libselection.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libselection.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libwa_refocus_extraphoto.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libwa_refocus_extraphoto.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libxcrash.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libxcrash.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libxcrash_dumper.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libxcrash_dumper.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/system/priv-app/MiuiExtraPhoto/lib/arm64/libyuv.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/MiuiExtraPhoto/lib/arm64/libyuv.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib/android.hardware.camera.provider@2.4-legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.camera.provider@2.4-legacy.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/android.hardware.camera.provider@2.4-legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.camera.provider@2.4-legacy.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libanc_dc_plugin_xiaomi_v2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libanc_dc_plugin_xiaomi_v2.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libmiStereoFactoryRemapBasicLib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiStereoFactoryRemapBasicLib.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libmiStereoFactoryRemapLib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiStereoFactoryRemapLib.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libmiStereoFactoryRemapLib_v2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmiStereoFactoryRemapLib_v2.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libwa_dof.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwa_dof.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libwa_refocus.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwa_refocus.so \
    vendor/xiaomi/mojito-leicacamera/proprietary/vendor/lib64/libwa_rtdof.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwa_rtdof.so

PRODUCT_PACKAGES += \
    MiuiCamera \
    MiuiExtraPhoto \
    MiuiScanner
